version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./poetry.lock:/app/poetry.lock:rw
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./poetry.lock:/app/poetry.lock:rw
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: